#dubbo:
#  application:
#    name: dubbo-provider
#  registry:
#    address: zookeeper://192.168.10.227:2181

# 加载其他配置文件,加载其他application-*.yml文件，多个名称之间使用逗号分隔
spring:
  profiles:
    active: mybatis
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: nacos://127.0.0.1:8848
